### ISSUE TITLE
The "Set as default launcher" and "Double tap to lock" features are not working until...

### ISSUE THREAD

**Issue by dilruk25** [neophtex/AsterLauncher#8]
First, I want to say that I love this application so much. I have noticed a few issues that might be good to fix:

1. **"Set as Default Launcher"** Option: This option is not working. When I click on it, the app quits.

2. **"Double Tap to Lock"** Feature: This feature does not work until I manually set the accessibility service on my Samsung Galaxy device. After setting it up, most issues are resolved. However, the app still becomes stuck while playing Samsung Music in the background.

I hope these issues can be addressed soon. Thank you for creating such a great application for free.

---

Feel free to tweak it further if needed!

**Comment by neophtex** [comment]
Thank you for your feedback, and sorry for the late reply.

1.I have fixed the issues with setting as the default launcher and double-tap to lock. Please update to the latest version.
2.Regarding the issue of the app getting stuck, please provide your device model and system version so that I can check it.

Thank you!

**Comment by dilruk25** [comment]
You're welcome...

I am using a Samsung Galaxy M14 with Android 14 (One UI 6.0)

**Comment by neophtex** [comment]
ok, thank you
